=== OfficeDev/teams-toolkit/schemas/declarativeCopilotSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "instructions": {
            "type": "string"
        },
        "capabilities": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/$defs/capabilities/web-search"
                    },
                    {
                        "$ref": "#/$defs/capabilities/graphic-art"
                    },
                    {
                        "$ref": "#/$defs/capabilities/code-interpreter"
                    },
                    {
                        "$ref": "#/$defs/capabilities/onedrive-and-sharepoint"
                    },
                    {
                        "$ref": "#/$defs/capabilities/sharepoint"
                    },
                    {
                        "$ref": "#/$defs/capabilities/onedrive"
                    },
                    {
                        "$ref": "#/$defs/capabilities/graph-connectors"
                    }
                ]
            }
        },
        "conversation_starters": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/conversation-starter"
            }
        },
        "actions": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/$defs/action-object"
                    }
                ]
            }
        }
    },
    "required": [
        "name",
        "description"
    ],
    "propertyNames": {
        "enum": [
            "id",
            "name",
            "description",
            "instructions",
            "capabilities",
            "conversation_starters",
            "actions",
            "$schema"
        ]
    },
    "$defs": {
        "capabilities": {
            "web-search": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "WebSearch"
                    }
                },
                "required": [
                    "name"
                ],
                "propertyNames": {
                    "enum": [
                        "name"
                    ]
                }
            },
            "graphic-art": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "GraphicArt"
                    }
                },
                "required": [
                    "name"
                ],
                "propertyNames": {
                    "enum": [
                        "name"
                    ]
                }
            },
            "code-interpreter": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "CodeInterpreter"
                    }
                },
                "required": [
                    "name"
                ],
                "propertyNames": {
                    "enum": [
                        "name"
                    ]
                }
            },
            "onedrive-and-sharepoint": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "OneDriveAndSharePoint"
                    },
                    "items_by_sharepoint_ids": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/sharepoint-ids"
                        }
                    },
                    "items_by_url": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/sharepoint-url"
                        }
                    }
                },
                "required": [
                    "name"
                ],
                "propertyNames": {
                    "enum": [
                        "name",
                        "items_by_sharepoint_ids",
                        "items_by_url"
                    ]
                }
            },
            "sharepoint": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "SharePoint"
                    },
                    "files": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/file"
                        }
                    },
                    "sites": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/site"
                        }
                    }
                },
                "required": [
                    "name"
                ],
                "propertyNames": {
                    "enum": [
                        "name",
                        "files",
                        "sites"
                    ]
                }
            },
            "onedrive": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "OneDrive"
                    },
                    "files": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/file"
                        }
                    }
                },
                "required": [
                    "name",
                    "files"
                ],
                "propertyNames": {
                    "enum": [
                        "name",
                        "files"
                    ]
                }
            },
            "graph-connectors": {
                "type": "object",
                "properties": {
                    "name": {
                        "const": "GraphConnectors"
                    },
                    "connections": {
                        "type": "array",
                        "items": {
                            "$ref": "#/$defs/connection"
                        }
                    }
                },
                "required": [
                    "name",
                    "connections"
                ],
                "propertyNames": {
                    "enum": [
                        "name",
                        "connections"
                    ]
                }
            }
        },
        "conversation-starter": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "text"
            ],
            "propertyNames": {
                "enum": [
                    "text",
                    "title"
                ]
            }
        },
        "action-object": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "file": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "file"
            ],
            "propertyNames": {
                "enum": [
                    "id",
                    "file"
                ]
            }
        },
        "sharepoint-ids": {
            "type": "object",
            "properties": {
                "site_id": {
                    "type": "string"
                },
                "web_id": {
                    "type": "string"
                },
                "list_id": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            },
            "propertyNames": {
                "enum": [
                    "site_id",
                    "web_id",
                    "list_id",
                    "unique_id"
                ]
            },
            "additionalProperties": false
        },
        "sharepoint-url": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            },
            "propertyNames": {
                "enum": [
                    "url"
                ]
            },
            "additionalProperties": false
        },
        "file": {
            "type": "object",
            "properties": {
                "site_id": {
                    "type": "string"
                },
                "web_id": {
                    "type": "string"
                },
                "list_id": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                }
            },
            "propertyNames": {
                "enum": [
                    "site_id",
                    "web_id",
                    "list_id",
                    "unique_id",
                    "file_name"
                ]
            },
            "additionalProperties": false
        },
        "site": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                }
            },
            "required": [
                "path",
                "site_name"
            ],
            "propertyNames": {
                "enum": [
                    "path",
                    "site_name"
                ]
            }
        },
        "connection": {
            "type": "object",
            "properties": {
                "connection_id": {
                    "type": "string"
                }
            },
            "required": [
                "connection_id"
            ],
            "propertyNames": {
                "enum": [
                    "connection_id"
                ]
            }
        }
    }
}

=== OfficeDev/teams-toolkit/packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/resources/gpt.json
{
    "name": "name${{APP_NAME_SUFFIX}}",
    "description": "description",
    "instructions": "instruction",
    "conversation_starters": [
        { "text": "text1"},
        { "text": "text2"}
    ],
    "actions": [
        {
            "file": "ai-plugin.json",
            "id": "plugin1"
        }
    ]
}
